
<script language="javascript" type="text/javascript">
<!--
function mm_reloadpage(init) {  //reloads the window if nav4 resized
  if (init==true) with (navigator) {if ((appname=="netscape")&&(parseint(appversion)==4)) {
    document.mm_pgw=innerwidth; document.mm_pgh=innerheight; onresize=mm_reloadpage; }}
  else if (innerwidth!=document.mm_pgw || innerheight!=document.mm_pgh) location.reload();
}
mm_reloadpage(true);
//-->
</script>


<style type="text/css">
<!--
#dw {
	color: #333300;
	font-size: x-large;
	font-family: "courier new", courier, mono;
}
-->
</style>
	<!-- #include file="../cab.asp" -->

	<!-- #include file="../menu.asp" -->

	<!-- #include file="../sites.asp" -->
 	<!-- #include file="../buscador.asp" -->
	<!-- #include file="../recomendado.asp" -->

	<!-- #include file="../arquivo.asp" -->

	<div id="txtcont">

<h2>tableless no dreamweaver mx 2004
</h2>
<p>por <a href="mailto:fred@flashmasters.com.br">frederick van amstel</a></p>
<p><img src="tablelessdw/screeshot_tutorial_dw.gif" alt="painél tag inspector em ação" width="178" height="254" align="right">boas novas para quem ainda n&atilde;o aderiu ao layout sem tabelas s&oacute; porque o dreamweaver n&atilde;o fazia isso automagicamente: nessa vers&atilde;o ele est&aacute; quase l&aacute;. a renderiza&ccedil;&atilde;o do css &eacute; quase perfeita, tal qual os browsers ir&atilde;o mostrar. o velho painel properties permite alterar alguma formata&ccedil;&atilde;o em css, mas &eacute; o pain&eacute;l tag inspector que &eacute; o grande show: mostra todas as op&ccedil;&otilde;es poss&iacute;veis com apenas um clique.</p>
<p>o dreamweaver pode melhorar a produtividade at&eacute; mesmo de quem j&aacute; domina css, porque ele mostra o resultado da formata&ccedil;&atilde;o em tempo real. para o designer que est&aacute; testando cores de fundo, bordas e fontes isso &eacute; uma m&atilde;o-na-roda. agora quem n&atilde;o souber css, n&atilde;o se preocupe, o dream ensina. al&eacute;m do pain&eacute;l com a refer&ecirc;ncia completa dos c&oacute;digos do css, ele conta o autocompletar que exibe at&eacute; a paleta de cores se for o caso.</p>
<p><img src="tablelessdw/screeshot_tutorial_dw2.gif" alt="automcompletar até com a paleta de cores" width="202" height="123" align="left">antes de entrar na pr&aacute;tica, voc&ecirc; precisa entender para que serve esse bendito css. a web n&atilde;o &eacute; um meio visual, como parece. o html foi criado para que pudesse ser acessado em qualquer dispositivo, seja visual ou n&atilde;o (ex: telefone via sintetizador de voz). isso significa texto puro. entretanto,  o html teve que ser distorcido para ser mais atrativo visualmente na web comercial. a&iacute; ficou essa lixeira de &lt;td&gt; pra c&aacute;, &lt;td&gt; pra l&aacute;. a codifica&ccedil;&atilde;o a m&atilde;o dessa &eacute;poca afungentou designers, que n&atilde;o gostam dessas complica&ccedil;&otilde;es. com o css isso acabou. agora t&aacute; tudo separado: conte&uacute;do no html, formata&ccedil;&atilde;o no css. totalmente deglut&iacute;vel.</p>
<p><img src="tablelessdw/screeshot_tutorial_dw3.gif" alt="código leve e fácil de ler" width="272" height="160" align="right">antes o dreamweaver era a salva&ccedil;&atilde;o do designer, porque escondia toda essa sujeira embaixo do tapete. com o css isso n&atilde;o &eacute; mais preciso e designers tamb&eacute;m podem escrever o c&oacute;digo na m&atilde;o, tranquilamente. o dreamweaver agora n&atilde;o deve mais ser usado como muleta, mas sim como bicicleta. saber escrever o c&oacute;digo se for preciso, mas usar os recursos do software para aumentar a velocidade de produ&ccedil;&atilde;o. </p>
<p><img src="tablelessdw/screeshot_tutorial_dw4.gif" alt="uma típica página sem formatação" width="130" height="318" align="left">ok, vamos come&ccedil;ar logo duma vez. primeiro, crie o documento html e cole todo o conte&uacute;do que voc&ecirc; vai colocar na p&aacute;gina. coloque na ordem de import&acirc;ncia, de cima para baixo, os textos e as imagens. separe os blocos relacionados usando a tag &lt;hr&gt; (insert &gt; html &gt; horizontal rule). selecione o t&iacute;tulo principal do texto e mude do tipo paragraph para heading 1 na barra properties. use o heading 2 para o segundo mais importante e assim por diante. </p>
<p>n&atilde;o se preocupe com a apar&ecirc;ncia grotesca que isso est&aacute; ficando, porque a formata&ccedil;&atilde;o arruma tudo isso. o importante agora &eacute; dar estrutura ao documento. se no documento, vai haver um menu, isso significa uma lista de links. ent&atilde;o use uma &lt;ul&gt; (s&oacute; selecionar os par&aacute;grafos com as op&ccedil;&otilde;es do menu e clicar no bot&atilde;o unordered list na barra properties). insira imagens normalmente, mas n&atilde;o se preocupe com o alinhamento delas, deixe no padr&atilde;o. </p>
<p>&eacute; nessa fase que o dreamweaver faz a c&oacute;difica&ccedil;&atilde;o na m&atilde;o comer poeira. o c&oacute;digo sai perfeito, n&atilde;o &eacute; preciso se preocupar com indenta&ccedil;&atilde;o nem nada mais. </p>
<p>agora, voc&ecirc; vai separar o conte&uacute;do em blocos principais que comp&otilde;em a p&aacute;gina. selecione conte&uacute;do e clique em menu insert &gt; layout objects &gt; div tag. na tela que aparece preencha o campo id com o conte&uacute;do que cont&eacute;m esse bloco (ex: cabecalho, menu, conteudoprincipal, topicosrelacionados, etc). <img src="tablelessdw/screeshot_tutorial_dw5.gif" alt="fio vermelho em volta do div" width="204" height="156" align="right">repare que em volta desse conte&uacute;do aparece uma fina borda vermelha se o mouse passa por cima dela. se voc&ecirc; j&aacute; tiver esbo&ccedil;ado o layout em outro software mais r&aacute;pido para alterar cores e posicionamento, como photoshop, corel ou o pr&oacute;prio flash essa fase fica mais f&aacute;cil. </p>
<p>terminou? pare e olhe bem o documento que voc&ecirc; estruturou. d&aacute; pra entender e navegar por ele desse jeito? &eacute;, porque vai ser assim que usu&aacute;rios de palmtops e o rob&ocirc; do google ir&atilde;o ler o seu documento, s&oacute; pra voc&ecirc; ter uma id&eacute;ia de como isso &eacute; importante. </p>
<p>certo, agora antes de come&ccedil;ar a colocar as coisas nos seus devidos lugares, voc&ecirc; precisa entender dois conceitos do css: float e position. o primeiro &eacute; mole. <img src="tablelessdw/screeshot_tutorial_dw7.gif" alt="exemplo de float" width="125" height="69" align="right">lembra do posicionamento <code>align = left / right</code> da tag &lt;img&gt;? &eacute; a mesma coisa, s&oacute; que pode ser aplicado a uma caixa de texto. o texto principal corre em volta da caixa de texto. </p>
<p>o segundo conceito define o posicionamento da caixa de texto em rela&ccedil;&atilde;o ao lugar onde ela est&aacute; (relative) ou de acordo com a janela do browser (absolute). o relativo &eacute; simples. <img src="tablelessdw/screeshot_tutorial_dw6.gif" alt="exemplo de posicionamento relativo" width="81" height="121" align="left">voc&ecirc; tem duas caixas, uma em cima da outra e quer que a de baixo fique 15px &agrave; direita em rela&ccedil;&atilde;o &agrave; outra, formando uma escadinha. quando h&aacute; muitos elementos na p&aacute;gina, trabalhar com o posicionamento relativo &eacute; mais dif&iacute;cil.</p>
<p>&eacute; poss&iacute;vel e mais f&aacute;cil criar uma p&aacute;gina s&oacute; usando o posicionamento absoluto (fa&ccedil;a alguns testes usando menu insert &gt; layout objects &gt; layer). para onde voc&ecirc; arrastar a moldura do layer, &eacute; onde ele ser&aacute; exibido no browser, nem mais nem menos. por&eacute;m, isso &eacute; problem&aacute;tico se voc&ecirc; precisar mudar o tamanho do texto de uma das caixas. ser&aacute; preciso reorganizar todas as outras, tal qual pagemaker, corel draw. isso fica impratic&aacute;vel se for usada uma folha de estilos para v&aacute;rias p&aacute;ginas. por isso, evite o posicionamento absoluto e s&oacute; use quando n&atilde;o conseguir fazer o que se pretende nem com o relativo nem com o float. </p>
<p>talvez voc&ecirc; esteja pensando porque est&aacute; lendo isso. &quot;t&aacute; muito mais complicado do que as velhas tabelas, isso nunca vai poder ser mais r&aacute;pido, esse cara me enganou.&quot; tenha calma. assim que voc&ecirc; se familiarizar com esses poucos conceitos, vai estar detonando, acredite. </p>
<p><img src="tablelessdw/screeshot_tutorial_dw8.gif" width="92" height="66" align="right">agora s&oacute; falta voc&ecirc; dominar o uso de dois pain&eacute;is: layers e tag inspector. clica no bot&atilde;o new css style no painel layers (aba css styles), escreva <code>#menu</code> e selecione a op&ccedil;&atilde;o advanced. se voc&ecirc; ainda n&atilde;o tiver criado uma folha de estilos para esse documento, agora voc&ecirc; ter&aacute; a oportunidade. <img src="tablelessdw/screeshot_tutorial_dw9.gif" width="124" height="142" align="left">na tela que aparece, voc&ecirc; tem &agrave; disposi&ccedil;&atilde;o todas as op&ccedil;&otilde;es de formata&ccedil;&atilde;o do css agrupadas pelos aspectos que afetam. esse menu &eacute; &oacute;timo para aprender css, mas &eacute; lento para quem j&aacute; manja. se voc&ecirc; est&aacute; sempre com pressa como eu,  preenche de qualquer jeito e use o pain&eacute;l tag inspector depois para arrumar.</p>
<p>procure pelo atributo float. coloca left e veja o que acontece. gostou? se n&atilde;o &eacute; isso que voc&ecirc; queria, voc&ecirc; pode tentar o posicionamento relativo ou absoluto. procure o atributo position e preencha com relative ou absolute. use os atributos top, right, bottom e left para trabalhar com esses posicionamentos. vai testando a&iacute;, n&atilde;o vale &agrave; pena explicar o &oacute;bvio. </p>
<p>ao mesmo tempo em que voc&ecirc; est&aacute; definindo o posicionamento das coisas voc&ecirc; j&aacute; pode ir adicionando a formata&ccedil;&atilde;o. na caixa menu, voc&ecirc; pode querer usar uma fonte menor, ent&atilde;o s&oacute; achar o atributo font-size e colocar smaller, ou o que for. d&aacute; pra mudar a cor de fundo, usar uma imagem de fundo e controlar se ela se repete ou n&atilde;o (no-repeat, repeat-x, repeat-y), alterar o espa&ccedil;amento entre letras e linhas e muito mais. </p>
<p>e esse menu horr&iacute;vel que ficou cheio de bolinhas? f&aacute;cil tirar. crie uma nova regra de css (painel layers, bot&atilde;o new css style) e escreva <code>#menu ul</code> e, &eacute; claro, escolha advanced. achar o atributo line-style-type e colocar none some com as bolinhas simpl&oacute;rias. definir padding e margin como 0  acaba com indenta&ccedil;&atilde;o in&uacute;til. display inline  disp&otilde;e os links numa barra horizontal, lado a lado. note como essa regra s&oacute; afetou a lista que est&aacute; dentro do menu, porque voc&ecirc; especificou isso em <code>#menu ul</code>. se tivesse usado s&oacute; ul tinha afetado todas as listas.</p>
<p class="style2"><img src="tablelessdw/screeshot_tutorial_dw10.gif" width="227" height="280" align="right">se voc&ecirc; gosta de cor-de-rosa, deve ter pensado que pode mudar s&oacute; a cor de fundo das op&ccedil;&otilde;es do menu usando #menu li com o atributo color: #ffccc. para finalizar, voc&ecirc; adiciona uma borda pink #ff00ff de 1 pixel de largura. voc&ecirc; pode at&eacute; usar imagens de fundo para dar mais luxo ao alegre menu. </p>
<p class="style2">para mudar o que voc&ecirc; j&aacute; definiu, voc&ecirc; pode usar o pain&eacute;l layers (que lista todas os seletores da folha de estilo), a barra properties (as op&ccedil;&otilde;es mais comuns de formata&ccedil;&atilde;o) e o pain&eacute;l tag inspector. este &uacute;ltimo tem duas abas maneiras, atrributes para alterar uma regra de css e relevant css para mudar os estilos que tem a ver com a tag onde o cursor se encontra. esse &eacute; arretado!</p>
<p>ok, voc&ecirc; j&aacute; pegou o processo. pode seguir em frente, por conta p&oacute;pria que voc&ecirc; j&aacute; descobre as manhas para formatar s&oacute; usando css. s&oacute; lhe dou uma dica: n&atilde;o pare por aqui. continue estudando esse assunto, porque tem muita coisa interessante para descobrir. prover acessibilidade, lidar com bugs dos browsers, criar layouts fluidos e fazer tutoriais bem-humorados, por exemplo, s&atilde;o desafios que todo webdesigner deve aprender a enfrentar.</p>
<p>notas: para implodir aquelas horrendas barras horizontais do exemplo use o c&oacute;digo <code>hr { display: none; }</code> . se seu dreamweaver mx 2004 anda travando, baixa a atualiza&ccedil;&atilde;o que corrige bugs e aumenta a perfomance. </p>
<p><a href="http://www.olenhador.org/fred/">frederick van amstel</a> &eacute; webdesigner e editor do blog <a href="http://www.olenhador.org/usabilidoido/">usabilidoido</a> </p>
</body>
</html>
