adRec("fechaTag (br)","http://elcio.locaweb.com.br/blog/")
adRec("Mobile (br)","http://www.rigonatti.com.br/mobile/")
adRec("Atípico (br)","http://www.atipico.com.br/")
adRec("Site de Poesias (br)","http://www.sitedepoesias.kit.net/")
adRec("Blog dos Poetas (br)","http://www.tableless.com.br/poetas")
adRec("Eyesmiles (br)","http://www.tableless.com.br/eyesmiles/")
adRec("Ana Beskow (br)","http://www.ana.beskow.nom.br/")
adRec("Superfície Reflexiva (br)","http://reflectivesurface.com/weblog-br/")
adRec("Jonas Galvez (br)","http://www.jonasgalvez.com/br/blog/")
adRec("Usabilidade na Web (br)","http://www.usabilidadenaweb.blogger.com.br/")
adRec("Ana Beskow (br)","http://www.ana.beskow.nom.br/")
adRec("Design Dojo","http://www.designdojo.ca/")
adRec("Mulligans","http://www.mulliganspub.it/")
adRec("Marquess Jobs","http://www.marquessjobs.com/")
adRec("Message Digital Design","http://www.message.uk.com/")
adRec("Jeffrey Zeldman","http://www.zeldman.com/")
adRec("Css Zen Garden","http://www.csszengarden.com/")
adRec("Skinnyj","http://skinnyj.com/weblog/")
adRec("ReadyMade","http://www.readymademag.com/")
adRec("Adam Polselli","http://www.adampolselli.com/")
adRec("Play Ground Blues","http://www.playgroundblues.com/")
adRec("Xlab","http://www.xlab.co.uk/")
adRec("PvComics","http://www.pvcomics.com/")
adRec("Just Watch Thesky","http://www.justwatchthesky.com/")
adRec("Joel on Software","http://brazil.joelonsoftware.com/")
adRec("Andy Budd","http://www.andybudd.com/blog/")